routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProdukController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Admin\ProductController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('depan');
});

Route::prefix('admin')->namespace('Admin')->group(static function() {
        Route::resource('produk', 'ProductController');
});

Route::get('awal','HomeController@dataProduk')->name('awal');
Route::get('formproduk','HomeController@formproduk')->name('formproduk');
Route::get('daftarbarang','HomeController@daftarBarang')->name('daftarbarang');

Route::get('depan',[ProdukController::class,'dataProduk']);
// Route::POST('/produk','ProdukController@store')->name('produk');
// Route::get('awal','ProdukController@create')->name('formproduk');
// Route::get('/create','ProdukController@create')->name('create');
Route::POST('formproduk',[ProdukController::class,'store']);

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// Route::prefix('user')->group(function () {
//     Route::resource('produk', 'ProdukController');
// });

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Produk;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $produks = Produk::all();
        return view('backand.product.index',compact([
            'produks'
        ]));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backand.product.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);
        $produks = new Produk;
        if ($image = $request->file('image')) {
            $destinationPath = 'img/';
            $imageName = date('YmdHis') . "." . $image->getClientOriginalExtension();
            $image->move($destinationPath, $imageName);
            $input['image'] = "$imageName";
        }else{
            unset($input['image']);
        }
        $produks ->jenis = $request->jenis;
        $produks ->type = $request->type;
        $produks ->hight = $request->hight;
        $produks ->wight = $request->wight;
        $produks ->gender = $request->gender;
        // dd($produks);

        $produks ->save();
        return back()->with('success','Data berhasil dibuat');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $produks = Produk::all();
        $produks = Produk::find($id);
        return view('backand.product.update');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $produks = Produk::find($id);
        $produks ->jenis = $request->jenis;
        $produks ->type = $request->type;
        $produks ->hight = $request->hight;
        $produks ->wight = $request->wight;
        $produks ->gender = $request->gender;
        // dd($produks);

        $produks ->save();
        return back()->with('success','Data berhasil diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $produks = Produk::findOrFail($id);
        $produks->delete();
        return back()->with('success', 'Data berhasil di hapus');
    }
}

resources/views/backand/product/create.blade.php
@extends('layouts.master')

@section('title')
Jarvis Farm
@endsection

@section('title-content')
Farm
@endsection

@section('content')
<div class="container">
    <div class="col-md-12">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <h1 class="h1 pb-4 py-3">Tambah Data Produk</h1>
            <div class="card mt-2">
                <div class="card-header">{{ __('Data Produk') }}</div>
                <div class="card-body">
                    @if ($message = Session::get('success'))
            <div class="alert alert-success alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <strong>{{ $message }}</strong>
            </div>
            @endif
            @if (count($errors) > 0)
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
                    <form action="{{route('produk.store')}}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="row">
                        <div class="col-6">
                        <div class="form-group">
                        <label for="jenis">Jenis</label>
                        <select class="form-control form-control-sm" name="jenis">
                            <option value="">Pilih jenis produk</option>
                            <option value="Sapi">Sapi</option>
                            <option value="Kambing">Kambing</option>
                            <option value="Domba">Domba</option>
                        </select>
                        </div>
                        <div class="form-group">
                            <label for="type">Type</label>
                            <select name="type" id="" class="form-control">
                                <option value="" >Pilih type produk</option>
                                <option value="Type A">type A</option>
                                <option value="Type B">type B</option>
                                <option value="Type C">type C</option>
                                <option value="Type D">type D</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="gender">JenisKelamin</label>
                            <select name="gender" id="" class="form-control">
                                <option value="" >Pilih jenis kelamin</option>
                                <option value="Jantan">Jantan</option>
                                <option value="Betina">Betina</option>
                            </select>
                        </div>
                    </div>
                        <div class="col-6">
                        <div class="form-group">
                            <label for="hight">Tinggi</label>
                            <input type="text" name="hight" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="wight">Berat</label>
                            <input type="text" name="wight" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="image">Upload Gambar</label>
                            <div class="custom-file">
                                <input type="file" class="custom-file-input @error('image') is-invalid @enderror" id="image" name="image" value="tes">
                                <label class="custom-file-label" for="image">Pilih gambar</label>
                                @error('image')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                        </div>
                    </div>
                </div>
                <br>
                    <button type="submit" class="btn btn-primary">Create</button>
                    
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
@endsection

resources/views/backand/product/index.blade.php
@extends('layouts.master')

@section('title')
Jarvis Farm
@endsection()

@section('title-content')
Farm
@endsection()

@section('content')
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">@yield('title-content')</h1>
        <a href="{{ route('produk.create') }}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
                class="fas fa-plus fa-sm text-white-50"></i> Add Product</a>
    </div>

    <!-- DataTales Example -->
<div class="card shadow mb-4">
<div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary">Data Product</h6>
</div>
<div class="card-body">
    <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>id</th>
                    <th>jenis</th>
                    <th>type</th>
                    <th>berat</th>
                    <th>tinggi</th>
                    <th>gender</th>
                    <th>aksi</th>
                </tr>
            </thead>
            <tbody>
                @foreach($produks as $produk)
                <tr>
                    <td>{{ $produk->id }}</td>
                    <td>{{ $produk->jenis }}</td>
                    <td>{{ $produk->type }}</td>
                    <td>{{ $produk->hight }}</td>
                    <td>{{ $produk->wight }}</td>
                    <td>{{ $produk->gender}}</td>
                    <td>
                        <a href="{{ route('produk.edit', $produk->id) }}" class="btn btn-primary btn-sm"><i class="fas fa-pencil-alt"></i></a>
                        <form action="{{ route("produk.destroy", $produk->id) }}" method="POST" class="form-inline">
                            @method('DELETE')
                            @csrf
                            <button class="btn btn-sm btn-danger rounded-0" onclick="return confirm('Apakah anda yakin untuk menghapus data ini?')" style=""><i class="fa fa-trash"></i></button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
</div>
@endsection()

resources/views/backand/product/update.blade.php
@extends('layouts.master')

@section('title')
Jarvis Farm
@endsection

@section('title-content')
Farm
@endsection

@section('content')
<div class="container">
    <div class="col-md-12">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <h1 class="h1 pb-4 py-3">Ubah Data Produk</h1>
            <div class="card mt-2">
                <div class="card-header">{{ __('Data Produk') }}</div>
                <div class="card-body">
                    @if ($message = Session::get('success'))
            <div class="alert alert-success alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <strong>{{ $message }}</strong>
            </div>
            @endif
            @if (count($errors) > 0)
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
                    <form action="{{route('produk.update', $produk->id)}}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @isset($produk)
                            {{ method_field('PATCH') }}
                        @endisset
                        <div class="row">
                        <div class="col-6">
                        <div class="form-group">
                        <label for="jenis">Jenis</label>
                        <select class="form-control form-control-sm @error('jenis') is-invalid @enderror" name="jenis">
                            <option value="">Pilih jenis produk</option>
                            <option value="Sapi">Sapi</option>
                            <option value="Kambing">Kambing</option>
                            <option value="Domba">Domba</option>
                        </select>
                        </div>
                        <div class="form-group">
                            <label for="type">Type</label>
                            <select name="type" id="" class="form-control">
                                <option value="" >Pilih type produk</option>
                                <option value="Type A">type A</option>
                                <option value="Type B">type B</option>
                                <option value="Type C">type C</option>
                                <option value="Type D">type D</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="gender">JenisKelamin</label>
                            <select name="gender" id="" class="form-control">
                                <option value="" >Pilih jenis kelamin</option>
                                <option value="Jantan">Jantan</option>
                                <option value="Betina">Betina</option>
                            </select>
                        </div>
                    </div>
                        <div class="col-6">
                        <div class="form-group">
                            <label for="hight">Tinggi</label>
                            <input type="text" name="hight" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="wight">Berat</label>
                            <input type="text" name="wight" class="form-control">
                        </div>
                    </div>
                </div>
                <br>
                    <button type="submit" class="btn btn-primary">Create</button>
                    
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
@endsection